version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wishes
      MYSQL_ROOT_PASSWORD: iva123  # Set the root password here
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
